import os

dirname = os.path.dirname(__file__)

class Config(object):
    SECRET_KEY = os.environ.get('SECRET_KEY') or 'you-will-never-guess'
    path_to_phenotypedb = '/media/database/phenotype.db'
    doc2hpo_default = "The proband (Individual IV-1) (see Fig. 2A) was observed to have bilateral clubfeet at 20 wk gestation via ultrasound. In early infancy, the Ponseti method was used to correct the clubfeet with serial casting, followed by bilateral Achilles tenotomy, and corrective shoes with a foot abduction orthosis (Ponseti et al. 2006). Additionally, it was noted that he had difficulty opening his hands because of flexion contractures of the fingers and was treated with hand splints and occupational therapy that improved his range of motion. Upon physical exam, the proband was observed to have some mild craniofacial dysmorphic features including a space between the upper teeth (diastema), ankyloglossia, a round face, down-slanted palpebral fissures with ptosis of the left eyelid, a short, upturned nose with a well-formed philtrum, and small, low-set ears with overfolded helices (Fig. 1A). Additionally, an ophthalmologic exam revealed farsightedness and astigmatism bilaterally, a genital exam revealed a mild shawl scrotum and bilateral undescended testes, and a Still's murmur was appreciated on physical exam (data not shown). His feet at most recent exam have reduced creases on the plantar surfaces and residual metatarsus adductus (Fig. 1B). The individual's hands showed a single palmar crease on the right and a transitional crease on the left with mild flexion contractures of the fingers, brachydactyly, and bilateral clinodactyly (Fig. 1C). The proband did not display microcephaly. There was a strong family history of craniofacial abnormalities, hand contractures, and clubfeet that segregated in an X-linked pattern (Fig. 2A). The proband has two maternal half uncles with similar features, including craniofacial dysmorphisms and hand contractures (Individuals III-4 and III-5 in Fig. 2A). One uncle also had bilateral clubfeet (III-4 in Fig. 2A), whereas the other uncle has a ventricular septal defect (III-5) (Fig. 2A). In addition, multiple affected male relatives were reported in at least two earlier generations, and two individuals were diagnosed with supraventricular tachycardia in addition to the observed skeletal abnormalities (Table 1). Taken together, this family represented a multigenerational pedigree with a prominent X-linked skeletal syndrome characterized by distal joint contractures and craniofacial abnormalities with the occurrence of cardiac abnormalities in multiple affected individuals."
    doc2hpo_url = "https://doc2hpo.wglab.org/parse/acdat" #"http://impact2.dbmi.columbia.edu/doc2hpo/parse/acdat" # can return to HTTPS when Columbia renews SSL cert and fixes site permanently
    elasticsearch_url = "elasticsearch:9200"
    path_to_headers = os.path.join(dirname, 'static/text/headers.txt')
    db_name = "/media/database/querycount.db"

