version: '3'

services:
    elasticsearch: # Elasticsearch Instance
        container_name: elastic-search
        image: docker.elastic.co/elasticsearch/elasticsearch:7.8.1
        volumes: # Persist ES data in separate "esdata" volume
            - /media/database/esdata:/usr/share/elasticsearch/data
            - ./elasticsearch.yml:/usr/share/elasticsearch/config/elasticsearch.yml
        environment:
            - bootstrap.memory_lock=true
            - "ES_JAVA_OPTS=-Xms750m -Xmx750m"
            - discovery.type=single-node
        ports: # Expose Elasticsearch ports
            - "9300:9300"
            - "9200:9200"
    app: # flask app
        container_name: phencards
        build: .
        ports:
            - "5005:5005" # Expose flask port
        environment: # Set ENV vars
            - NODE_ENV=local
            - ES_HOST=elasticsearch
        volumes: # Attach local book data directory
            - /media/database:/media/database
        depends_on:
            - elasticsearch


# volumes: # Define separate volume for Elasticsearch data
#   esdata:
